/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmr.ventanas;

import com.jmr.operaciones.DistanciaOp;
import com.jmr.MetodosNumeros.ConversorDeStrings;
import com.jmr.MetodosNumeros.EliminarNotacion;

/**
 *
 * @author JMaRod
 */
public class Distancias extends javax.swing.JFrame
{

    DistanciaOp distanciaOp = new DistanciaOp();
    /**
     * Creates new form Distancias
     */
    public Distancias()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabelDistanciasTitulo = new javax.swing.JLabel();
        jButtonDistanciasRetorno = new javax.swing.JButton();
        jLabelDistanciasValor = new javax.swing.JLabel();
        jTextFieldDistanciasIngreso = new javax.swing.JTextField();
        jComboBoxDistanciasEntradas = new javax.swing.JComboBox<>();
        jComboBoxDistanciasSalidas = new javax.swing.JComboBox<>();
        jLabelDistanciasUnidadOrigen = new javax.swing.JLabel();
        jLabelDistanciasUnidadDestino = new javax.swing.JLabel();
        jLabelDistanciasResultado = new javax.swing.JLabel();
        jTextFieldDistanciasResultado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneDistanciasInstrucciones = new javax.swing.JTextPane();
        jLabelDistanciasFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDistanciasTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDistanciasTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDistanciasTitulo.setText("Distancias");
        jLabelDistanciasTitulo.setMaximumSize(new java.awt.Dimension(52, 22));
        jLabelDistanciasTitulo.setMinimumSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabelDistanciasTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 80, 30));

        jButtonDistanciasRetorno.setText("Regresar");
        jButtonDistanciasRetorno.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDistanciasRetornoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDistanciasRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabelDistanciasValor.setText("Valor a convertir:");
        getContentPane().add(jLabelDistanciasValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 20));

        jTextFieldDistanciasIngreso.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldDistanciasIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDistanciasIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 130, -1));

        jComboBoxDistanciasEntradas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "centímetro", "metro", "kilómetro", "pie", "pulgada" }));
        jComboBoxDistanciasEntradas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxDistanciasEntradasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDistanciasEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, -1));

        jComboBoxDistanciasSalidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "centímetro", "metro", "kilómetro", "pie", "pulgada" }));
        jComboBoxDistanciasSalidas.setSelectedIndex(1);
        jComboBoxDistanciasSalidas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxDistanciasSalidasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDistanciasSalidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 130, -1));

        jLabelDistanciasUnidadOrigen.setText("Unidad de origen:");
        getContentPane().add(jLabelDistanciasUnidadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 20));

        jLabelDistanciasUnidadDestino.setText("Unidad de destino:");
        getContentPane().add(jLabelDistanciasUnidadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 20));

        jLabelDistanciasResultado.setText("Resultado:");
        getContentPane().add(jLabelDistanciasResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 20));

        jTextFieldDistanciasResultado.setEditable(false);
        jTextFieldDistanciasResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jTextFieldDistanciasResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 130, -1));

        jTextPaneDistanciasInstrucciones.setEditable(false);
        jTextPaneDistanciasInstrucciones.setText("Seleccione una unidad de origen, despues una unidad de destino.\nA continuación ingrese la cantidad en \"Valor a convertir\".\nPor último presiones Enter.");
        jTextPaneDistanciasInstrucciones.setCaretPosition(0);
        jScrollPane2.setViewportView(jTextPaneDistanciasInstrucciones);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 380, 70));

        jLabelDistanciasFondo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelDistanciasFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDistanciasRetornoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDistanciasRetornoActionPerformed
    {//GEN-HEADEREND:event_jButtonDistanciasRetornoActionPerformed
        Intro intro = new Intro();
        this.setVisible(false);
        intro.setVisible(true);
    }//GEN-LAST:event_jButtonDistanciasRetornoActionPerformed

    private void jTextFieldDistanciasIngresoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldDistanciasIngresoActionPerformed
    {//GEN-HEADEREND:event_jTextFieldDistanciasIngresoActionPerformed
        float numero = ConversorDeStrings.revisarNumeroSinCero(evt.getActionCommand());
        jTextFieldDistanciasResultado.setText(String.valueOf(numero));
        seleccionarEntrada(jComboBoxDistanciasEntradas.getSelectedItem(), jComboBoxDistanciasSalidas.getSelectedItem(), numero);
    }//GEN-LAST:event_jTextFieldDistanciasIngresoActionPerformed

    private void jComboBoxDistanciasSalidasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxDistanciasSalidasActionPerformed
    {//GEN-HEADEREND:event_jComboBoxDistanciasSalidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDistanciasSalidasActionPerformed

    private void jComboBoxDistanciasEntradasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxDistanciasEntradasActionPerformed
    {//GEN-HEADEREND:event_jComboBoxDistanciasEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDistanciasEntradasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDistanciasRetorno;
    private javax.swing.JComboBox<String> jComboBoxDistanciasEntradas;
    private javax.swing.JComboBox<String> jComboBoxDistanciasSalidas;
    private javax.swing.JLabel jLabelDistanciasFondo;
    private javax.swing.JLabel jLabelDistanciasResultado;
    private javax.swing.JLabel jLabelDistanciasTitulo;
    private javax.swing.JLabel jLabelDistanciasUnidadDestino;
    private javax.swing.JLabel jLabelDistanciasUnidadOrigen;
    private javax.swing.JLabel jLabelDistanciasValor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldDistanciasIngreso;
    private javax.swing.JTextField jTextFieldDistanciasResultado;
    private javax.swing.JTextPane jTextPaneDistanciasInstrucciones;
    // End of variables declaration//GEN-END:variables

    private void seleccionarEntrada(Object entrada, Object salida, float numero)
    {
        if (entrada == "centímetro" && salida == "centímetro")
                imprimirResultado(0);
        else if (entrada == "centímetro" && salida == "metro")
                imprimirResultado(distanciaOp.centimetrosAMetro(numero));
        else if (entrada == "centímetro" && salida == "kilómetro")
                imprimirResultado(distanciaOp.centimetrosAKilometro(numero));
        else if (entrada == "centímetro" && salida == "pie")
                imprimirResultado(distanciaOp.centimetrosAPie(numero));
        else if (entrada == "centímetro" && salida == "pulgada")
                imprimirResultado(distanciaOp.centimetrosAPulgada(numero));
        else if (entrada == "metro" && salida == "centímetro")
                imprimirResultado(distanciaOp.metrosACentimetros(numero));
        else if (entrada == "metro" && salida == "metro")
                imprimirResultado(0);
        else if (entrada == "metro" && salida == "kilómetro")
                imprimirResultado(distanciaOp.metrosAkilometros(numero));
        else if (entrada == "metro" && salida == "pie")
                imprimirResultado(distanciaOp.metrosAPie(numero));
        else if (entrada == "metro" && salida == "pulgada")
                imprimirResultado(distanciaOp.metrosAPulgadas(numero));
        else if (entrada == "kilómetro" && salida == "centímetro")
                imprimirResultado(distanciaOp.kilometrosACentimetro(numero));
        else if (entrada == "kilómetro" && salida == "metro")
                imprimirResultado(distanciaOp.kilometrosAMetro(numero));
        else if (entrada == "kilómetro" && salida == "kilómetro")
                imprimirResultado(0);
        else if (entrada == "kilómetro" && salida == "pie")
                imprimirResultado(distanciaOp.kilometrosAPie(numero));
        else if (entrada == "kilómetro" && salida == "pulgada")
                imprimirResultado(distanciaOp.kilometrosAPulgada(numero));
        else if (entrada == "pie" && salida == "centímetro")
                imprimirResultado(distanciaOp.pieAMetro(numero));
        else if (entrada == "pie" && salida == "metro")
                imprimirResultado(distanciaOp.pieAMetro(numero));
        else if (entrada == "pie" && salida == "kilómetro")
                imprimirResultado(distanciaOp.pieAkilometro(numero));
        else if (entrada == "pie" && salida == "pie")
                imprimirResultado(0);
        else if (entrada == "pie" && salida == "pulgada")
                imprimirResultado(distanciaOp.pieAPulgadas(numero));
        else if (entrada == "pulgada" && salida == "centímetro")
                imprimirResultado(distanciaOp.pulgadasACentimetro(numero));
        else if (entrada == "pulgada" && salida == "metro")
                imprimirResultado(distanciaOp.pulgadasAMetro(numero));
        else if (entrada == "pulgada" && salida == "kilómetro")
                imprimirResultado(distanciaOp.pulgadasAKilometro(numero));
        else if (entrada == "pulgada" && salida == "pie")
                imprimirResultado(distanciaOp.pulgadasAPies(numero));
        else if (entrada == "pulgada" && salida == "pulgada")
                imprimirResultado(0);

    }
    
    public void imprimirResultado(double numero){
        jTextFieldDistanciasResultado.setText(EliminarNotacion.eliminarNotaciónCientífica(numero));
    }
}
