/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmr.ventanas;

/**
 *
 * @author JMaRod
 */
public class Intro extends javax.swing.JFrame
{

    /**
     * Creates new form Intro
     */
    public Intro()
    {
        initComponents();
        
        this.setLocationRelativeTo(null);//para que la ventana salga en el centro de la pantalla
                                         //para quitar los bordes y los botnes de ventana en 
                                         //las opciones de Desing del [Jframe] hay que activar
                                         //la opción Undecorated
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1SalirIntro = new javax.swing.JButton();
        jLabelInstruccionesIntro = new javax.swing.JLabel();
        jLabelTituloIntro = new javax.swing.JLabel();
        jButtonDivisas = new javax.swing.JButton();
        jButtonDistancias = new javax.swing.JButton();
        jButtonTemperaturas = new javax.swing.JButton();
        jButtonTiempo = new javax.swing.JButton();
        jLabelFondoIntro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1SalirIntro.setText("Salir");
        jButton1SalirIntro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1SalirIntroActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1SalirIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 150, -1));

        jLabelInstruccionesIntro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabelInstruccionesIntro.setForeground(new java.awt.Color(255, 255, 51));
        jLabelInstruccionesIntro.setText("Selecciona una Opción");
        getContentPane().add(jLabelInstruccionesIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 30));

        jLabelTituloIntro.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTituloIntro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 26)); // NOI18N
        jLabelTituloIntro.setForeground(new java.awt.Color(255, 255, 51));
        jLabelTituloIntro.setText("Programa Conversiones");
        getContentPane().add(jLabelTituloIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 260, 30));

        jButtonDivisas.setText("Divisas");
        jButtonDivisas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDivisasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDivisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, -1));

        jButtonDistancias.setText("Distancias");
        jButtonDistancias.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDistanciasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDistancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, -1));

        jButtonTemperaturas.setText("Temperaturas");
        jButtonTemperaturas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonTemperaturasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTemperaturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, -1));

        jButtonTiempo.setText("Tiempo");
        jButtonTiempo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));

        jLabelFondoIntro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoIntrop.jpg"))); // NOI18N
        jLabelFondoIntro.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelFondoIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SalirIntroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1SalirIntroActionPerformed
    {//GEN-HEADEREND:event_jButton1SalirIntroActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1SalirIntroActionPerformed

    private void jButtonDivisasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDivisasActionPerformed
    {//GEN-HEADEREND:event_jButtonDivisasActionPerformed
        // TODO add your handling code here:
        Divisas conversiones = new Divisas();
        this.setVisible(false);
        conversiones.setVisible(true);
        
    }//GEN-LAST:event_jButtonDivisasActionPerformed

    private void jButtonDistanciasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDistanciasActionPerformed
    {//GEN-HEADEREND:event_jButtonDistanciasActionPerformed
        Distancias distancias = new Distancias();
        this.setVisible(false);
        distancias.setVisible(true);
    }//GEN-LAST:event_jButtonDistanciasActionPerformed

    private void jButtonTemperaturasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonTemperaturasActionPerformed
    {//GEN-HEADEREND:event_jButtonTemperaturasActionPerformed
        Temperaturas temperaturas = new Temperaturas();
        this.setVisible(false);
        temperaturas.setVisible(true);
    }//GEN-LAST:event_jButtonTemperaturasActionPerformed

    private void jButtonTiempoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonTiempoActionPerformed
    {//GEN-HEADEREND:event_jButtonTiempoActionPerformed
        Tiempos tiempos = new Tiempos();
        this.setVisible(false);
        tiempos.setVisible(true);
    }//GEN-LAST:event_jButtonTiempoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1SalirIntro;
    private javax.swing.JButton jButtonDistancias;
    private javax.swing.JButton jButtonDivisas;
    private javax.swing.JButton jButtonTemperaturas;
    private javax.swing.JButton jButtonTiempo;
    private javax.swing.JLabel jLabelFondoIntro;
    private javax.swing.JLabel jLabelInstruccionesIntro;
    private javax.swing.JLabel jLabelTituloIntro;
    // End of variables declaration//GEN-END:variables
}
